{
 "title": "Income",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "FuelBlock", "label": "Fuel Block", "query": "18000" },
   { "name": "Corp1", "label": "Corp1", "query": "98663301" },
   { "name": "Corp2", "label": "Corp2", "query": "98000682" },
   { "name": "Corp3", "label": "Corp3", "query": "98630647" },
   { "name": "Corp4", "label": "Main Corp", "query": "98660859" }
  ]
 },
 "panels": [
  {
   "title": "Calendar Month Income",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  month(date) as time,\r\n  sum(amount) as \"Total Monthly Income\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), month(date)\r\nORDER BY year(date) DESC, month(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  month(date) as time,\r\n  sum(amount) / day(CURRENT_TIMESTAMP) as \"Average Income Per Day\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), month(date)\r\nORDER BY year(date) DESC, month(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  month(date) as time,\r\n  sum(amount) as \"Total Monthly Expense\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), month(date)\r\nORDER BY year(date) DESC, month(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  month(date) as time,\r\n  IF(ISNULL(sum(amount))=1, 0, sum(amount)) / day(CURRENT_TIMESTAMP) as \"Avg. Daily Maint. Cost\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), month(date)\r\nORDER BY year(date) DESC, month(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  month(date) as time,\r\n  sum(amount) as \"Total Monthly Net\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\")\r\nGROUP BY year(date), month(date)\r\nORDER BY year(date) DESC, month(date) DESC"
    }
   ]
  },
  {
   "title": "Main Wallet Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    cw.balance, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $Corp4 and cw.division_id = 1\norder BY $__timeGroup(cw.date,'5m')"
    }
   ]
  },
  {
   "title": "SRP Wallet Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    cw.balance, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $Corp4 and cw.division_id = 6\norder BY $__timeGroup(cw.date,'5m')"
    }
   ]
  },
  {
   "title": "Calendar Weekly Income",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  week(date) as time,\r\n  sum(amount) as \"Total Weekly Income\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), week(date)\r\nORDER BY year(date) DESC, week(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  week(date) as time,\r\n  sum(amount) / 7 as \"Average Income Per Day\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), week(date)\r\nORDER BY year(date) DESC, week(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  week(date) as time,\r\n  sum(amount) as \"Total Weekly Expense\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), week(date)\r\nORDER BY year(date) DESC, week(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  week(date) as time,\r\n  sum(amount) / 7 as \"Avg. Daily Maint. Cost\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), week(date)\r\nORDER BY year(date) DESC, week(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  month(date) as time,\r\n  sum(amount) as \"Total Weekly Net\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\")\r\nGROUP BY year(date), month(date)\r\nORDER BY year(date) DESC, month(date) DESC"
    }
   ]
  },
  {
   "title": "Chart of income",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time,\r\n  ref_type,\r\n  sum(amount) as \"Total\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"contract_price\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), month(date), ref_type\r\nORDER BY year(date) DESC, month(date) DESC"
    }
   ]
  },
  {
   "title": "Chart of Expenses",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time,\r\n  ref_type,\r\n  if(sum(amount) > 0, 0, sum(amount) * -1)  as \"Total\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"contract_price\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), month(date), ref_type\r\nORDER BY year(date) DESC, month(date) DESC"
    }
   ]
  },
  {
   "title": "Calendar Daily Income",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  day(date) as time,\r\n  sum(amount) as \"Total Daily Income\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), day(date)\r\nORDER BY year(date) DESC, day(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  day(date) as time,\r\n  sum(amount) / 24 as \"Average Income Per Hour\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY year(date), day(date)\r\nORDER BY year(date) DESC, day(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  day(date) as time,\r\n  sum(amount) as \"Total Daily Expense\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), day(date)\r\nORDER BY year(date) DESC, day(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  day(date) as time,\r\n  sum(amount) / 24 as \"Avg. Hourly Maint. Cost\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND ref_type != \"market_provider_tax\"\r\n  AND amount < 0)\r\nGROUP BY year(date), day(date)\r\nORDER BY year(date) DESC, day(date) DESC"
    },
    {
     "rawSql": "SELECT\r\n  day(date) as time,\r\n  sum(amount) as \"Total Daily Net\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\")\r\nGROUP BY year(date), day(date)\r\nORDER BY year(date) DESC, day(date) DESC"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    cw.balance, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $Corp4\norder BY $__timeGroup(cw.date,'5m')"
    }
   ]
  },
  {
   "title": "SRP Wallet Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    cw.balance, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = 6\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $Corp4\norder BY $__timeGroup(cw.date,'1m')"
    }
   ]
  },
  {
   "title": "Fuel Cost per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400))*$FuelBlock,\r\n  ss.fuel_expires_at as \"time\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND owner_id = 1\r\n  AND si.eve_type_id != 16273\r\ngroup by time"
    }
   ]
  },
  {
   "title": "Fuel Cost per Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400))*$FuelBlock)*28,\r\n  ss.fuel_expires_at as \"time\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND owner_id = 1\r\n  AND si.eve_type_id != 16273\r\ngroup by time"
    }
   ]
  },
  {
   "title": "Fuel Blocks per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400)),\r\n  ss.fuel_expires_at as \"time\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND owner_id = 1\r\n  AND si.eve_type_id != 16273\r\ngroup by time"
    }
   ]
  },
  {
   "title": "Fuel Blocks per Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400))*7,\r\n  ss.fuel_expires_at as \"time\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND owner_id = 1\r\n  AND si.eve_type_id != 16273\r\ngroup by time"
    }
   ]
  },
  {
   "title": "Fuel Blocks per Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400))*30,\r\n  ss.fuel_expires_at as \"time\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND owner_id = 1\r\n  AND si.eve_type_id != 16273\r\ngroup by time"
    }
   ]
  },
  {
   "title": "Wallet - Raw",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select\n    cw.date, cw.amount, cw.description, cw.reason, cw.ref_type, cw.division_id, cw.balance\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere $__timeFilter(date) and cinfo.corporation_id = 98660859"
    }
   ]
  },
  {
   "title": "Example Corp Tax To Alliance",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Ratting Income\",\r\n  (sum(amount)/0.05)*0.05 as \"Total Monthly Tax Owed\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere cinfo.corporation_id = '98664079'\r\n  AND $__timeFilter(date)\r\n  AND (ref_type = \"bounty_prizes\"\r\n  OR ref_type = \"ess_escrow_transfer\")\r\n  AND year(date) = 2022\r\nGROUP BY year(date), month(date), 1\r\nORDER BY year(date) DESC, month(date) DESC, 1"
    }
   ]
  },
  {
   "title": "Total Monthly Income Before Sov",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income Before Sov\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type != \"player_donation\" \r\n  AND ref_type != \"corporation_account_withdrawal\"\r\n  AND amount > 0\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Total Monthly Income After Sov",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income After Sov\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"planetary_export_tax\" \r\n  OR ref_type = \"planetary_import_tax\"\r\n  OR ref_type = \"reprocessing_tax\"\r\n  OR ref_type = \"industry_job_tax\"\r\n  OR ref_type = \"brokers_fee\"\r\n  OR ref_type = \"ess_escrow_transfer\"\r\n  OR ref_type = \"bounty_prizes\"\r\n  OR ref_type = \"corporate_reward_payout\"\r\n  OR ref_type = \"structure_gate_jump\"\r\n  OR ref_type = \"jump_clone_installation_fee\"\r\n  OR ref_type = \"market_provider_tax\"\r\n  OR ref_type = \"infrastructure_hub_maintenance\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Total Daily Income",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'1d') as time_sec,\r\n  sum(amount) as \"Daily Income\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"planetary_export_tax\" \r\n  OR ref_type = \"planetary_import_tax\"\r\n  OR ref_type = \"reprocessing_tax\"\r\n  OR ref_type = \"industry_job_tax\"\r\n  OR ref_type = \"brokers_fee\"\r\n  OR ref_type = \"ess_escrow_transfer\"\r\n  OR ref_type = \"bounty_prizes\"\r\n  OR ref_type = \"corporate_reward_payout\"\r\n  OR ref_type = \"structure_gate_jump\"\r\n  OR ref_type = \"jump_clone_installation_fee\"\r\n  OR ref_type = \"market_provider_tax\")\r\nGROUP BY 1\r\nORDER BY 1 DESC"
    }
   ]
  },
  {
   "title": "Total Monthly Sov Cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) * -1 as \"Total Monthly Maintenance Cost\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND ref_type = \"infrastructure_hub_maintenance\"\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Reprocessing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'24h') as time_sec,\r\n  sum(amount),\r\n  ref_type as metric\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"reprocessing_tax\")\r\nGROUP BY 1, 3\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly Reprocessing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"reprocessing_tax\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Ratting",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'24h') as \"time\",\r\n  sum(amount) as \"Daily Ratting Income\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"bounty_prizes\" OR ref_type = \"ess_escrow_transfer\")\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly Ratting",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"ess_escrow_transfer\"\r\n  OR ref_type = \"bounty_prizes\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Market",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'24h') as time_sec,\r\n  sum(amount) / 2 as total,\r\n  ref_type as metric\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"brokers_fee\")\r\nGROUP BY 1, 3\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly Market",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"brokers_fee\" OR ref_type = \"market_provider_tax\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Jump Gate Fees",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'24h') as \"time\",\r\n  sum(amount) as \"Total Isk\",\r\n  sum(amount)/count(ref_type) as \"Average Isk per Jump\",\r\n  sum(amount)/500 as \"LO Burnt\",\r\n  count(ref_type) as \"Jumps\",\r\n  (sum(amount)/500)/count(ref_type) as \"Average LO per Jump\"\r\nFROM \r\n  corptools_corporationwalletjournalentry\r\nWHERE\r\n  $__timeFilter(date) AND ref_type = \"structure_gate_jump\"\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly Jump Gate Fees",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Year(date) as \"Year\",\r\n  Month(date) as \"Month\",\r\n  sum(amount) as \"Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Income Diff.\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"Income % Diff.\",\r\n  count(ref_type) as \"Jumps\",\r\n  ceil(sum(amount)/750) as \"LO Burnt\"\r\nFROM \r\n  corptools_corporationwalletjournalentry\r\nWHERE $__timeFilter(date) and ref_type = \"structure_gate_jump\"\r\nGROUP BY 1, 2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Industry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'24h') as time_sec,\r\n  sum(amount),\r\n  ref_type as metric\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"industry_job_tax\")\r\nGROUP BY 1, 3\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly Industry",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"industry_job_tax\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Planetary Interaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'1d') as time_sec,\r\n  sum(amount),\r\n  ref_type as metric\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"planetary_export_tax\" OR ref_type = \"planetary_import_tax\")\r\nGROUP BY 1, 3\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly PI",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"planetary_export_tax\" \r\n  OR ref_type = \"planetary_import_tax\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Incursion",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(date,'24h') as time_sec,\r\n  sum(amount),\r\n  ref_type as metric\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date) \r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"corporate_reward_payout\")\r\nGROUP BY 1, 3\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Monthly Incursion",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(date) as \"Year\",\r\n  month(date) as \"Month\",\r\n  sum(amount) as \"Total Monthly Income\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(amount) - LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) asc))/ LAG (sum(amount)) OVER (ORDER BY year(date) asc, month(date) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM \r\n  corptools_corporationwalletjournalentry cw\r\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\r\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\r\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\r\nwhere $__timeFilter(date)\r\n  AND (cinfo.corporation_id = $Corp1\r\n  OR cinfo.corporation_id = $Corp2\r\n  OR cinfo.corporation_id = $Corp3\r\n  OR cinfo.corporation_id = $Corp4)\r\n  AND (ref_type = \"corporate_reward_payout\")\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "LO In JBs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ss.name as \"Name\",\r\n  SUM(si.quantity) as \"LO Left\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND ss.owner_id = 1\r\n  AND si.eve_type_id = 16273\r\nGROUP BY 1\r\nORDER BY 2 ASC"
    }
   ]
  },
  {
   "title": "Total Monthly SRP Paid Out",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  year(post_time) as \"Year\",\r\n  month(post_time) as \"Month\",\r\n  sum(payout_amount) AS \"SRP\",\r\n  (sum(payout_amount) - LAG (sum(payout_amount)) OVER (ORDER BY year(post_time) asc, month(post_time) asc)) AS \"Amount Difference From Previous\",\r\n  (sum(payout_amount) - LAG (sum(payout_amount)) OVER (ORDER BY year(post_time) asc, month(post_time) asc))/ LAG (sum(payout_amount)) OVER (ORDER BY year(post_time) asc, month(post_time) ASC) * 100 AS \"% Difference From Previous\"\r\nFROM aasrp_aasrprequest\r\nWHERE $__timeFilter(post_time)\r\nGROUP BY 1,2\r\nORDER BY 1 DESC, 2 DESC"
    }
   ]
  },
  {
   "title": "Fuel In Structures",
   "type": "table",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ss.name as \"Name\",\r\n  SUM(si.quantity) as \"Fuel Left\",\r\n  SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400)) as \"Fuel Per Day\",\r\n  SUM(si.quantity) / SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400)) as \"Days of Fuel Left\",\r\n  ss.fuel_expires_at as \"Expiration\",\r\n  36 / (SUM(si.quantity) / SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400))) * (SUM(si.quantity / ((UNIX_TIMESTAMP(ss.fuel_expires_at) - UNIX_TIMESTAMP()) / 86400))) + 1296 as \"Fuel needed to be 36 days\"\r\nFROM structures_structureitem si\r\n  INNER JOIN structures_structure ss ON si.structure_id = ss.id\r\nWHERE si.location_flag = \"StructureFuel\"\r\n  AND ss.owner_id = 1\r\n  AND si.eve_type_id != 16273\r\nGROUP BY 5, 1\r\nORDER BY 5 ASC"
    }
   ]
  }
 ]
}